version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Starting pre_build. Install npm dependencies
      - npm install
  build:
    commands:
      - echo Starting build
      - npm run build
artifacts:
  files:
    - build/**/*