export { default as counter } from './counter';
export { default as newquiz } from '../newquiz/newquizform';
export { default as editcategory } from '../editcategory/categoryform';
export { default as welcome } from './welcome';
export { default as main } from './mainlayout';
export { default as editquestion } from '../editquestion';
export { default as editcategoryview } from './editcategoryview'
export { default as editcategorylist } from './editcategorylist'
export { default as editcategorysuccess } from './editcategorysuccess'